# Generated by Django 4.1.2 on 2022-12-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libman', '0003_auto_20180526_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='barcode',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.CharField(choices=[('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022')], max_length=4),
        ),
    ]
